import { lazy, Suspense, useState } from 'react'
import { ArrowLeft, ArrowRight, BadgeCheck, Check, CircleAlert, ReceiptText, Star, Store, Users, Wallet, X } from 'lucide-react'
import { gameAssets } from '../../assets/registry'
import { getWorkScenario } from '../../data/workShift'
import type { WorkScenarioChoice, WorkShiftDefinition, WorkShiftProgress, WorkWorldFlag } from '../../domain/types'
import { money } from '../smartmart/ShoppingProducts'

const WorkModeGame = lazy(() => import('../../game/WorkModeGame'))
const flagLabels: Record<WorkWorldFlag,string> = { 'complaint-risk': 'Khách có thể khiếu nại', 'pricing-mismatch': 'Cần kiểm tra giá', 'inventory-pressure': 'Lưu ý lượng hàng còn lại', 'cash-discrepancy': 'Cần kiểm tra tiền mặt', 'billing-dispute': 'Khách thắc mắc về hóa đơn', 'stale-promo-sign': 'Cần kiểm tra biển khuyến mãi' }

function SimulationMetrics({ progress }: { progress: WorkShiftProgress }) {
  return <div className="simulation-metrics"><div><Star size={22} /><span>Đánh giá nhân viên<strong>{progress.metrics.employeeRating.toFixed(1)}/5</strong></span></div><div><Store size={22} /><span>Uy tín cửa hàng<strong>{progress.metrics.storeReputation.toFixed(1)}/5</strong></span></div><div><Users size={22} /><span>Hài lòng khách<strong>{progress.metrics.customerSatisfaction.toFixed(1)}/5</strong></span></div><div><Wallet size={22} /><span>Doanh thu<strong>{money.format(progress.metrics.revenue)}đ</strong></span></div></div>
}

export function WorkResult({ shift, progress, onBack, onReplay }: { shift: WorkShiftDefinition; progress: WorkShiftProgress; onBack: () => void; onReplay: () => void }) {
  const entries = shift.customers.map(customer => progress.customerProgress[customer.id])
  const solved = entries.reduce((sum, item) => sum + Number(item?.totalSolved) + Number(item?.changeSolved), 0)
  const firstTry = entries.reduce((sum, item) => sum + Number(item?.totalSolved && item.totalAttempts === 1) + Number(item?.changeSolved && item.changeAttempts === 1), 0)
  const attempts = entries.reduce((sum, item) => sum + (item?.totalAttempts ?? 0) + (item?.changeAttempts ?? 0), 0)
  const scenarios = shift.customers.filter(customer => customer.scenarioId)
  const handled = scenarios.filter(customer => progress.customerProgress[customer.id]?.scenarioChoiceId).length
  return <section className="work-result-production"><button type="button" className="quiet-button" onClick={onBack}><ArrowLeft size={18} />Nhiệm vụ của em</button><header><img src={gameAssets.production.employee} alt="Nhân viên SmartMart" /><div><p className="eyebrow">MỘT CA LÀM, THÊM NHIỀU TRẢI NGHIỆM</p><h1>Hoàn thành ca làm!</h1><p>{shift.title} · {progress.metrics.servedCustomers}/{shift.customers.length} khách đã phục vụ</p></div><BadgeCheck size={58} aria-hidden="true" /></header>
    <section className="work-learning-results" aria-labelledby="work-learning-title"><h2 id="work-learning-title">Kết quả học tập và làm việc</h2><div className="learning-result-grid"><div><ReceiptText size={26} /><strong>{solved}/{shift.customers.length * 2}</strong><span>Phép tính hoàn thành</span><small>{firstTry} đúng ngay lần đầu · {attempts} lượt thử</small></div><div><Check size={26} /><strong>{handled}/{scenarios.length}</strong><span>Tình huống đã xử lý</span><small>Mỗi lựa chọn mang lại một kết quả riêng.</small></div><div><CircleAlert size={26} /><strong>{progress.worldState.resolvedConsequences.length}</strong><span>Hệ quả đã xảy ra</span><small>Cùng nhìn lại ảnh hưởng của quyết định.</small></div></div></section>
    <section className="simulation-result-section" aria-labelledby="simulation-title"><h2 id="simulation-title">Trạng thái mô phỏng</h2><p>Các chỉ số dưới đây phản ánh cửa hàng và khách hàng, <strong>không phải điểm học tập</strong>.</p><SimulationMetrics progress={progress} /></section>
    {progress.worldState.resolvedConsequences.length ? <section className="consequence-reflection"><h2>Nhìn lại những quyết định</h2>{progress.worldState.resolvedConsequences.map(item => <article key={item.instanceId}><CircleAlert size={20} /><div><h3>{item.title}</h3><p>{item.description}</p></div></article>)}</section> : null}
    <div className="work-result-actions"><button type="button" className="outline-button" onClick={onReplay}>Chơi lại ca làm</button><button type="button" className="adventure-button" onClick={onBack}>Tiếp tục hành trình<ArrowRight size={20} /></button></div>
  </section>
}

export function WorkCounter({ shift, progress, stage, answer, feedback, selectedChoice, baseTotal, effectiveTotal, expectedChange, onAnswer, onSubmit, onChoice, onContinue, onBack }: {
  shift: WorkShiftDefinition; progress: WorkShiftProgress; stage: 'total'|'scenario'|'change'|'done'; answer: string; feedback: 'idle'|'wrong'|'correct'; selectedChoice?: WorkScenarioChoice; baseTotal: number; effectiveTotal: number; expectedChange: number; onAnswer: (value: string) => void; onSubmit: () => void; onChoice: (choice: WorkScenarioChoice) => void; onContinue: () => void; onBack: () => void
}) {
  const [sceneOpen, setSceneOpen] = useState(false)
  const customer = shift.customers[progress.customerIndex]
  const scenario = customer.scenarioId ? getWorkScenario(customer.scenarioId) : null
  const customerProgress = progress.customerProgress[customer.id]
  const lastConsequence = progress.worldState.resolvedConsequences.at(-1)
  return <section className="work-production"><div className="shop-toolbar"><button type="button" className="quiet-button" onClick={onBack}><ArrowLeft size={18} />Nhiệm vụ</button><span className="work-shift-chip">Khách {progress.customerIndex + 1}/{shift.customers.length}</span></div>
    <header className="work-title"><div><p className="eyebrow">ĐANG VÀO CA · {shift.roleTitle}</p><h1>{shift.title}</h1></div><span><Store size={18} />SmartMart</span></header>
    <div className="pos-layout"><section className="customer-workspace"><div className="customer-scene"><div className="store-shelves" aria-hidden="true" /><img src={gameAssets.production.customers[progress.customerIndex % gameAssets.production.customers.length]} alt="" /><div className="customer-speech"><p className="eyebrow">KHÁCH HÀNG HIỆN TẠI</p><h2>{customer.name}</h2><p>{stage === 'scenario' && scenario ? scenario.description : stage === 'done' ? 'Cảm ơn em đã giúp mình mua sắm!' : stage === 'change' ? 'Mình gửi em tiền thanh toán nhé.' : 'Em tính giúp mình những món này nhé.'}</p></div><div className="checkout-counter-front"><ReceiptText size={24} /><span>QUẦY THU NGÂN</span></div></div>
      <div className="pos-receipt"><header><ReceiptText size={20} /><h2>Đơn hàng hiện tại</h2><span>{customer.basket.length} loại hàng</span></header><table><caption className="sr-only">Hóa đơn của {customer.name}</caption><thead><tr><th>Sản phẩm</th><th>SL</th><th>Đơn giá</th><th>Thành tiền</th></tr></thead><tbody>{customer.basket.map(item => <tr key={item.name}><th scope="row">{item.name}</th><td>{item.quantity}</td><td>{money.format(item.unitPrice)}đ</td><td>{money.format(item.unitPrice * item.quantity)}đ</td></tr>)}</tbody></table><div className="receipt-summary"><span>Tổng tiền hàng</span><strong>{customerProgress.totalSolved ? `${money.format(baseTotal)}đ` : 'Em hãy tính nhé'}</strong></div>{selectedChoice?.billDelta ? <div className="receipt-summary"><span>Điều chỉnh hóa đơn</span><strong>{selectedChoice.billDelta > 0 ? '+' : ''}{money.format(selectedChoice.billDelta)}đ</strong></div> : null}</div>
    </section>
    <section className="pos-action" aria-label="Tác vụ tại quầy" key={`${customer.id}-${stage}`}>
      {stage === 'scenario' && scenario ? <><p className="eyebrow">TÌNH HUỐNG TẠI QUẦY</p><h2>{scenario.title}</h2><p className="pos-question">Em sẽ xử lý như thế nào?</p><div className="scenario-options">{scenario.choices.map((choice,index) => <button key={choice.id} type="button" onClick={() => onChoice(choice)}><span className="choice-index">{index + 1}</span><span><strong>{choice.label}</strong>{choice.billDelta !== 0 ? <small>Hóa đơn {choice.billDelta < 0 ? 'giảm' : 'tăng'} {money.format(Math.abs(choice.billDelta))}đ</small> : <small>Giữ nguyên tổng hóa đơn</small>}</span><ArrowRight size={18} /></button>)}</div><p className="pos-hint">Hãy cân nhắc cả khách hàng và cửa hàng.</p></> : stage === 'done' ? <div className="pos-done" role="status"><BadgeCheck size={45} /><p className="eyebrow">GIAO DỊCH HOÀN TẤT</p><h2>Em đã phục vụ xong!</h2><p>Tiền thừa: <strong>{money.format(expectedChange)}đ</strong>.</p><button className="adventure-button" type="button" onClick={onContinue}>{progress.customerIndex === shift.customers.length - 1 ? 'Kết thúc ca' : 'Khách tiếp theo'}<ArrowRight size={19} /></button></div> : <>
        <p className="eyebrow">{stage === 'total' ? 'TÍNH HÓA ĐƠN' : 'TRẢ TIỀN THỪA'}</p><h2>{stage === 'total' ? 'Khách cần trả bao nhiêu?' : 'Trả lại khách bao nhiêu?'}</h2>
        {stage === 'change' ? <><div className="pos-payment"><div><span>Khách đưa</span><strong>{money.format(customer.cashGiven)}đ</strong></div><div><span>Cần thanh toán</span><strong>{money.format(effectiveTotal)}đ</strong></div></div>{selectedChoice ? <div className="decision-feedback"><Check size={19} /><p>{selectedChoice.feedback}</p></div> : null}</> : <p className="pos-question">Tính số lượng × đơn giá của từng món, rồi cộng lại.</p>}
        <form onSubmit={event => {event.preventDefault(); if(answer.trim()) onSubmit()}}><label htmlFor="pos-answer">{stage === 'total' ? 'Tổng hóa đơn' : 'Tiền thừa'}</label><div className="pos-input"><input id="pos-answer" inputMode="numeric" autoComplete="off" value={answer} onChange={event => onAnswer(event.target.value)} placeholder="Nhập số tiền" aria-describedby="pos-feedback" aria-invalid={feedback === 'wrong'} /><span>đồng</span></div><div className="pos-number-pad" aria-label="Bàn phím nhập tiền">{['1','2','3','4','5','6','7','8','9','000','0','backspace'].map(key => <button type="button" key={key} aria-label={key === 'backspace' ? 'Xóa chữ số cuối' : `Nhập ${key}`} onClick={() => onAnswer(key === 'backspace' ? answer.slice(0,-1) : answer + key)}>{key === 'backspace' ? <X size={21} /> : key}</button>)}</div><div id="pos-feedback" role="status" className={`pos-feedback ${feedback}`}>{feedback === 'wrong' ? 'Chưa đúng. Em kiểm tra lại phép tính nhé.' : feedback === 'correct' ? 'Đúng rồi! Cùng tiếp tục công việc.' : 'Em có thể dùng bàn phím số bên dưới hoặc nhập trực tiếp.'}</div><button type="submit" disabled={!answer.trim()} className="adventure-button">{stage === 'total' ? 'Kiểm tra hóa đơn' : 'Xác nhận tiền thừa'}<Check size={20} /></button></form>
      </>}
    </section></div>
    {(progress.worldState.flags.length > 0 || lastConsequence) ? <aside className="context-warning"><CircleAlert size={22} /><div>{lastConsequence ? <><strong>{lastConsequence.title}</strong><p>{lastConsequence.description}</p></> : <strong>Lưu ý trong ca làm</strong>}<div className="context-flags">{progress.worldState.flags.map(flag => <span key={flag}>{flagLabels[flag]}</span>)}</div></div></aside> : null}
    <details className="work-secondary"><summary>Hàng chờ và trạng thái mô phỏng · {Math.max(0, shift.customers.length - progress.customerIndex - 1)} khách đang chờ</summary><div className="compact-customer-queue">{shift.customers.map((item,index) => <div key={item.id}><img src={gameAssets.production.customers[index % gameAssets.production.customers.length]} alt="" /><strong>{item.name}</strong><span>{index < progress.customerIndex || index === progress.customerIndex && stage === 'done' ? 'Đã phục vụ' : index === progress.customerIndex ? 'Đang tại quầy' : 'Đang chờ'}</span></div>)}</div><p>Các chỉ số mô phỏng không phải điểm học tập.</p><SimulationMetrics progress={progress} /></details>
    <button className="quiet-button scene-toggle" type="button" aria-expanded={sceneOpen} onClick={() => setSceneOpen(!sceneOpen)}>{sceneOpen ? 'Thu gọn không gian quầy' : 'Xem không gian quầy'}</button>
    {sceneOpen ? <Suspense fallback={<p>Đang mở không gian quầy…</p>}><WorkModeGame customers={shift.customers} customerIndex={progress.customerIndex} stage={stage} selectedChoice={selectedChoice} worldFlags={progress.worldState.flags} /></Suspense> : null}
  </section>
}
