// Local browser smoke: run Vite first, then PLAYWRIGHT_MODULE_PATH=... node scripts/check-ui.mjs.
import assert from 'node:assert/strict'
import { createRequire } from 'node:module'
import { mkdir, writeFile } from 'node:fs/promises'
const require = createRequire(import.meta.url)
const { chromium } = require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright')
const browser = await chromium.launch({ channel: process.env.UI_BROWSER_CHANNEL || 'msedge', headless: true })
const baseURL = process.env.UI_BASE_URL || 'http://127.0.0.1:5173'
const results = []
await mkdir('output/ui-redesign', { recursive: true })
try {
  for (const [device, width, height] of [['desktop', 1440, 1080], ['tablet', 820, 1180], ['mobile', 390, 844]]) {
    const context = await browser.newContext({ viewport: { width, height }, reducedMotion: 'reduce' })
    const page = await context.newPage()
    const errors = []
    page.on('pageerror', err => errors.push(err.message))
    page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()) })
    page.on('response', response => { if (response.status() >= 400 && new URL(response.url()).origin === new URL(baseURL).origin) errors.push(response.status() + ' ' + response.url()) })
    const screenshot = async name => {
      await page.screenshot({ path: 'output/ui-redesign/' + name + '-' + device + '.png', fullPage: true })
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, name + ' page overflow on ' + device)
      const dialog = page.locator('dialog[open]')
      if (await dialog.count()) assert.equal(await dialog.evaluate(el => el.scrollWidth > el.clientWidth + 1), false, name + ' dialog overflow on ' + device)
    }
    await page.goto(baseURL, { waitUntil: 'networkidle' })
    await screenshot('world')
    await page.getByRole('button', { name: /Tạo nhân vật của em/ }).click()
    await page.getByRole('dialog').waitFor()
    await screenshot('avatar')
    await page.getByRole('button', { name: 'Màu da: Nâu ấm', exact: true }).click()
    await page.getByRole('button', { name: 'Hủy', exact: true }).click()
    assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('smartkid-wallet-avatar-v1') || '{}').state?.hasCreatedAvatar ?? false), false, 'Cancel must not create avatar')
    await page.getByRole('button', { name: /Tạo nhân vật của em/ }).click()
    await page.getByRole('button', { name: 'Màu da: Nâu ấm', exact: true }).click()
    await page.getByRole('tab').nth(1).click()
    await page.getByRole('button', { name: 'Tóc bob', exact: true }).click()
    await page.getByRole('button', { name: 'Kính', exact: true }).click()
    await screenshot('avatar-hair')
    await page.getByRole('tab').nth(2).click()
    await page.getByRole('button', { name: 'Màu áo: Cam san hô', exact: true }).click()
    await page.getByRole('tab').nth(3).click()
    await page.getByRole('button', { name: /Suy nghĩ/ }).click()
    await screenshot('avatar-expression')
    await page.getByRole('button', { name: 'Lưu nhân vật', exact: true }).click()
    await page.reload({ waitUntil: 'networkidle' })
    const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('smartkid-wallet-avatar-v1')).state)
    assert.equal(saved.avatar.skinTone, '#ba7956')
    assert.equal(saved.avatar.hairStyle, 'bob')
    assert.equal(saved.avatar.accessory, 'glasses')
    assert.equal(saved.avatar.topColor, '#dc7969')
    assert.equal(saved.avatar.expression, undefined, 'Preview expression must not change the saved avatar')
    assert.equal(saved.hasCreatedAvatar, true)
    await page.locator('.explorer-avatar-link').click()
    await page.getByRole('dialog').waitFor()
    const firstTab = page.getByRole('tab').first()
    await firstTab.focus()
    await page.keyboard.press('ArrowRight')
    assert.equal(await page.getByRole('tab').nth(1).getAttribute('aria-selected'), 'true')
    await page.keyboard.press('Escape')
    assert.equal(await page.getByRole('dialog').count(), 0)
    await page.getByRole('button', { name: 'Bắt đầu khám phá', exact: true }).click()
    await page.getByRole('heading', { name: 'Chào mừng đến SmartMart!' }).waitFor()
    await screenshot('smartmart')
    assert.equal(await page.locator('.hub-stall-food').isDisabled(), true)
    await page.locator('.hub-stall-produce').click()
    await page.getByRole('dialog').waitFor()
    const originalQuestion = await page.locator('.exercise-question').textContent()
    await screenshot('exercise')
    await page.getByRole('button', { name: 'Đóng bài Toán', exact: true }).click()
    await page.reload({ waitUntil: 'networkidle' })
    await page.getByRole('button', { name: 'Bắt đầu khám phá', exact: true }).click()
    await page.locator('.hub-stall-produce').click()
    assert.equal(await page.locator('.exercise-question').textContent(), originalQuestion, 'Issued exercise must remain stable after refresh')
    for (let step = 0; step < 3; step++) {
      const answer = await page.evaluate(async step => {
        const { generateExercise } = await import('/src/domain/exerciseEngine.ts')
        const { getExerciseFamilyById } = await import('/src/data/exerciseFamilies.ts')
        const { stalls } = await import('/src/data/stalls.ts')
        return generateExercise(getExerciseFamilyById(stalls[0].unlockFamilyIds[step]), 'student-demo-minh-anh', step).answer
      }, step)
      await page.getByLabel('Đáp án của em', { exact: true }).fill(String(answer))
      await page.getByRole('button', { name: 'Kiểm tra đáp án', exact: true }).click()
      await page.getByRole('button', { name: step === 2 ? 'Mở gian hàng' : 'Bài tiếp theo', exact: true }).click()
    }
    assert.equal(await page.locator('.hub-stall-food').isEnabled(), true)
    const progress = await page.evaluate(() => JSON.parse(localStorage.getItem('smartkid-wallet-progression-v4')).state)
    assert.equal(progress.unlockedStalls.includes('produce'), true)
    assert.equal(progress.unlockedStalls.includes('food'), false)
    await page.getByRole('button', { name: 'Trang chủ', exact: true }).click()
    await page.locator('.explorer-home').waitFor()
    await screenshot('home')
    await page.getByRole('button', { name: 'Nhân vật', exact: true }).click()
    await page.locator('.student-passport').waitFor()
    await screenshot('profile')
    await page.getByRole('button', { name: 'Nhiệm vụ', exact: true }).click()
    await page.locator('.missions-screen').waitFor()
    await screenshot('missions')
    await page.getByRole('button', { name: 'Xếp hạng', exact: true }).click()
    await page.locator('.class-leaderboard').first().waitFor({ timeout: 5000 }).catch(() => {})
    await screenshot('leaderboard')
    assert.deepEqual(errors, [], 'Browser errors on ' + device)
    results.push({ device, viewport: width + 'x' + height, avatarSaveCancelReload: 'passed', keyboard: 'passed', deterministicExercise: 'passed', mathUnlock: 'passed', overflow: false, errors })
    await context.close()
  }
  await writeFile('output/ui-redesign/results.json', JSON.stringify(results, null, 2))
  console.log(JSON.stringify(results, null, 2))
} finally { await browser.close() }
